### ISSUE TITLE
Please add a warning about EFS provisioned throughput costs

### ISSUE THREAD

**Issue by jeznag** [aws-samples/lambda-efs-deep-learning-inference#1]
I blindly copied/pasted the code from https://github.com/aws-samples/lambda-efs-deep-learning-inference/blob/master/cdk/index.ts without checking how EFS pricing works and checked my AWS bill 2 days later to discover a $1000 USD bill from EFS provisioned throughput. Please change your code sample to use something more reasonable or leave a big warning comment.

**Comment by giuseppeporcelli** [comment]
Hi, thanks for sharing your experience. Although the documentation was mentioning to destroy the resources after running the example, we have reduced EFS provisioned throughput (with a comment mentioning that has been kept low intentionally) to avoid this happening by chance again.
